# Numpy

Numpy is the primary way in python to handle matrices/vectors

In [2]:
import numpy as np
print(np.__version__)

1.13.3


## Array: the fundamental building block

### Creating arrays

In [3]:
a = np.array([1,2,3,4])
print("a:\n", a)
b = np.array([[1,2], [3,4]])
print("b:\n", b)

a:
 [1 2 3 4]
b:
 [[1 2]
 [3 4]]


In [4]:
## Shape: the form of the array
print(a.shape)
print(b.shape)

(4,)
(2, 2)


In [5]:
## create various arrays
print("arange:\n", np.arange(10))
# like range, but gives an array
print("zeros:\n", np.zeros((2,5)) )
print("ones:\n", np.ones_like((b)) )
print("empty:\n", np.empty((3,8)) )
print("reshape:\n", np.arange(12).reshape((3,4)), "\n")
print("random numbers:\n", np.random.randn(4,5) ,'\n')

arange:
 [0 1 2 3 4 5 6 7 8 9]
zeros:
 [[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
ones:
 [[1 1]
 [1 1]]
empty:
 [[ -1.49166815e-154  -4.33307931e-311   2.24710859e-314   2.24870200e-314
    2.24844751e-314   2.24677267e-314   2.24809759e-314   2.24844744e-314]
 [  2.24846056e-314   2.24713172e-314   2.24668102e-314   2.24845880e-314
    2.24680862e-314   2.24682404e-314   2.24713089e-314   2.24730820e-314]
 [  2.24807708e-314   2.24844740e-314   2.24656500e-314   2.24682343e-314
    2.24662674e-314   2.24668217e-314   2.24727505e-314   0.00000000e+000]]
reshape:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

random numbers:
 [[-0.68089302  2.04465375 -0.99503356  0.63595551  2.4831768 ]
 [ 0.94950764  3.74349557 -0.9735977  -0.52482551 -0.41593928]
 [-0.0858843  -0.63616236  0.47612786  0.0622631   0.93575681]
 [-0.29608747  1.68972371  0.27273342  1.12956382 -0.18645119]] 



In [6]:
## data types
print(a.dtype)
c = np.array([1,2], dtype='int64')
print(c)
print(c.dtype)
## converting data types
d = np.array([True,False,True])
print(d)
print(d.astype('float'))
# can also convert strings

int64
[1 2]
int64
[ True False  True]
[ 1.  0.  1.]


In [7]:
## math with arrays
print(1 + a, "\n")
print(2**b, "\n")  # note: exponent with **, not with ^

[2 3 4 5] 

[[ 2  4]
 [ 8 16]] 



### Array Indexing and Slicing

In [8]:
## 1d arrays indexed like lists:
a = np.arange(12)
print(a[::-1])
b = a
a[5:11] = -1
print(b)

[11 10  9  8  7  6  5  4  3  2  1  0]
[ 0  1  2  3  4 -1 -1 -1 -1 -1 -1 11]


In [9]:
## 2D arrays may need two indices:
c = np.arange(12).reshape((3,4))
print("c:\n", c, "\n")
print("2nd row:\n", c[1], "\n")
print("3rd column:\n", c[:,2], "\n")
print("2nd row, 3rd column:\n", c[1,2], '\n', c[1][2], '\n')

c:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

2nd row:
 [4 5 6 7] 

3rd column:
 [ 2  6 10] 

2nd row, 3rd column:
 6 
 6 



In [10]:
## 2d Slicing:
print("rows 1,2:\n", c[:2], '\n')
print("rows 1,2, cols 1,2,3:\n", c[:2, :3], '\n')

rows 1,2:
 [[0 1 2 3]
 [4 5 6 7]] 

rows 1,2, cols 1,2,3:
 [[0 1 2]
 [4 5 6]] 



In [11]:
## Slicing may give unexpected results
c = np.arange(12).reshape((3,4))
print("original c:\n", c)
d = c
d[1,] = -1
print("changed d:\n", d)
print("...but c changed too:\n", c)
## use 'copy' for deep copy
e = c.copy()
e[:,1] = -2
print("changed e:\n", e)
print("...now c is unchanged:\n", c)


original c:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
changed d:
 [[ 0  1  2  3]
 [-1 -1 -1 -1]
 [ 8  9 10 11]]
...but c changed too:
 [[ 0  1  2  3]
 [-1 -1 -1 -1]
 [ 8  9 10 11]]
changed e:
 [[ 0 -2  2  3]
 [-1 -2 -1 -1]
 [ 8 -2 10 11]]
...now c is unchanged:
 [[ 0  1  2  3]
 [-1 -1 -1 -1]
 [ 8  9 10 11]]


Exercise:
* create a 4x5 array of even numbers: 2, 4, 6, ...
* extract third column
* set the fourth row to 1,2,3,4,5

Note: there are many ways to achieve this.

In [12]:
a = np.arange(2,42,2).reshape(4,5)
print(a[:,2], '\n')
a[3] = 1 + np.arange(5)
a

[ 6 16 26 36] 



array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [ 1,  2,  3,  4,  5]])

In [ ]:
## do it here

In [15]:
## Boolean indexing
a = np.random.randn(4,3)
print(a, '\n')
b = np.zeros_like(a)
print(b, '\n')
b[a < 0] = -1
print(b, '\n')

[[-1.24528529  1.57555488 -0.40531846]
 [-0.92756631  0.4454403  -0.62246795]
 [ 0.83209177  1.23110972 -1.47658666]
 [ 0.57377793  1.13799246 -0.29851833]] 

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]] 

[[-1.  0. -1.]
 [-1.  0. -1.]
 [ 0.  0. -1.]
 [ 0.  0. -1.]] 



## Universal Functions  (ufuncs)

Vectorized arithmetic/logic on arrays

In [16]:
a = np.arange(12).reshape((3,4))
print("sqrt:\n", np.sqrt(a), '\n')
print("squares:\n", a**2, '\n')
b = np.arange(12)[::-1].reshape((3,4))
print(b)
print("powers:\n", np.power(a,b), '\n')
print(">", np.greater(a, b), '\n')


sqrt:
 [[ 0.          1.          1.41421356  1.73205081]
 [ 2.          2.23606798  2.44948974  2.64575131]
 [ 2.82842712  3.          3.16227766  3.31662479]] 

squares:
 [[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]] 

[[11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]
powers:
 [[    0     1   512  6561]
 [16384 15625  7776  2401]
 [  512    81    10     1]] 

> [[False False False False]
 [False False  True  True]
 [ True  True  True  True]] 



In [20]:
## Computing
a = np.arange(12).reshape((3,4))
np.where(a % 2 == 0, "even", "odd")

array([['even', 'odd', 'even', 'odd'],
       ['even', 'odd', 'even', 'odd'],
       ['even', 'odd', 'even', 'odd']],
      dtype='<U4')

In [22]:
b = np.random.uniform(size = (3,4))
print(b, '\n')
np.where(b > 0.5, 1, b)

[[ 0.85396976  0.38657821  0.22155888  0.87019432]
 [ 0.12743224  0.7979087   0.63044366  0.15470723]
 [ 0.72089466  0.28662082  0.85720324  0.57877022]] 



array([[ 1.        ,  0.38657821,  0.22155888,  1.        ],
       [ 0.12743224,  1.        ,  1.        ,  0.15470723],
       [ 1.        ,  0.28662082,  1.        ,  1.        ]])

In [23]:
## Stats
b.mean()

0.54052349448338177

In [24]:
## do this row-wise
## Note: axis 1 is columns.  sum(axis=1) means sum by columns, retain rows
b.sum(axis=1)

array([ 2.33230116,  1.71049184,  2.44348894])

In [25]:
b.argmin()

4

In [26]:
b.argmin(axis=0)

array([1, 2, 0, 1])

In [27]:
## sorting
a = np.random.uniform(size=10)
print(a, '\n')
a.sort()  # in-place sorting
print("a is sorted:\n", a)
a = np.random.uniform(size=10)
b = np.sort(a)  # returns sorted array
print("a is not sorted:\n", a)


[ 0.6937621   0.52772492  0.92491873  0.88122773  0.60574371  0.54672421
  0.03070399  0.74547764  0.2457965   0.18396989] 

a is sorted:
 [ 0.03070399  0.18396989  0.2457965   0.52772492  0.54672421  0.60574371
  0.6937621   0.74547764  0.88122773  0.92491873]
a is not sorted:
 [ 0.89156553  0.65774242  0.41744731  0.48071071  0.66576287  0.99202033
  0.26609858  0.52752595  0.56150031  0.29638352]
